Repository hmcts/rpx-xui-approve-org, pull requests merged in 2019-08, with the labels that each got.

#92 chaning endpoint to preview
  api/auth/index.ts
  api/lib/config/application.config.ts
  api/lib/config/environments/local.config.ts
  api/organisation/index.ts
  src/environments/environment.ts
  src/services/auth/auth.service.ts
Labels: ns:xui-ao-webapp-pr-92

#93 Feature/eui 539 logging aa
  src/app/app.module.ts
  src/org-manager/store/actions/org-pending.actions.ts
  src/org-manager/store/effects/org-pending-effects.spec.ts
  src/org-manager/store/effects/org-pending.effects.ts
  src/org-manager/store/effects/organisation.effects.spec.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/org-manager/store/effects/single-org-pending.effects.spec.ts
  src/org-manager/store/effects/single-org-pending.effects.ts
  src/org-manager/store/effects/single-org.effects.spec.ts
  src/org-manager/store/effects/single-org.effects.ts
  src/shared/errorHandler/defaultErrorHandler.spec.ts
  src/shared/errorHandler/defaultErrorHandler.ts
Labels: ns:xui-ao-webapp-pr-93

#90 EUI-518 getting rid of front end cookie removal
  src/app/store/effects/app.effects.ts
Labels: ns:xui-ao-webapp-pr-90

#95 organisation approval logger userid changes. Also logging succesful A…
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/services/CryptoWrapper.spec.ts
  src/app/services/cryptoWrapper.ts
  src/app/services/jwtDecodeWrapper.ts
  src/app/services/logger.service.spec.ts
  src/app/services/logger.service.ts
  src/org-manager/store/effects/org-pending-effects.spec.ts
  src/org-manager/store/effects/org-pending.effects.ts
  yarn.lock
Labels: ns:xui-ao-webapp-pr-95

#94 Restrict user by role
  api/auth/index.ts
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/local.config.ts
  api/lib/config/environments/preview.config.ts
  charts/xui-ao-webapp/values.aat.template.yaml
Labels: ns:xui-ao-webapp-pr-94

#97 add idam login urls to node config
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/local.config.ts
Labels: ns:xui-ao-webapp-pr-97

#100 commenting out the logger service to try
  src/app/app.module.ts
  src/org-manager/store/effects/org-pending.effects.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/org-manager/store/effects/single-org-pending.effects.ts
  src/org-manager/store/effects/single-org.effects.ts
  src/shared/errorHandler/defaultErrorHandler.spec.ts
  src/shared/errorHandler/defaultErrorHandler.ts
Labels: ns:xui-ao-webapp-pr-100

#103 Fix for security bug login refresh
  api/auth/index.ts
Labels: ns:xui-ao-webapp-pr-103

#98 EUI-583 replaced package, removed npm references and modified code
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  package-lock.json
  package.json
  test/e2e/support/reports.js
  yarn.lock
Labels: ns:xui-ao-webapp-pr-98

#106 added env var
  infrastructure/main.tf
Labels: ns:xui-ao-webapp-pr-106

#107 Refactor, clean up and make the approve Org details work
  api/lib/config/environments/local.config.ts
  api/organisation/index.ts
  src/app/utils/app-utils.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/org-manager/components/summary/summary.component.html
  src/org-manager/components/summary/summary.component.ts
  src/org-manager/services/organisation.service.ts
  src/org-manager/store/actions/single-org.actions.spec.ts
  src/org-manager/store/actions/single-org.actions.ts
  src/org-manager/store/effects/single-org.effects.spec.ts
  src/org-manager/store/effects/single-org.effects.ts
  src/org-manager/store/reducers/single-org.reducer.spec.ts
Labels: ns:xui-ao-webapp-pr-107

#125 Bug/eui 608 error interceptor
  api/lib/http.ts
  api/lib/interceptors.ts
  api/lib/util.ts
Labels: ns:xui-ao-webapp-pr-125

#126 Cookie policy. Privacy Policy and T&C's pages
  src/app/app.constants.ts
  src/app/app.routes.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.spec.ts
  src/app/containers/cookie-policy/cookie-policy.component.html
  src/app/containers/cookie-policy/cookie-policy.component.ts
  src/app/containers/index.ts
  src/app/containers/privacy-policy/privacy-policy.component.html
  src/app/containers/privacy-policy/privacy-policy.component.ts
  src/app/containers/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/terms-and-conditions/terms-and-conditions.component.ts
Labels: ns:xui-ao-webapp-pr-126

#133 Adding Logger/Appinsights/Default error Handler back now
  src/app/app.module.ts
  src/org-manager/store/effects/org-pending.effects.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/shared/errorHandler/defaultErrorHandler.spec.ts
  src/shared/errorHandler/defaultErrorHandler.ts
  src/shared/shared.module.ts
Labels: ns:xui-ao-webapp-pr-133

#134 AAT Setup changes EUI-673
  Jenkinsfile_CNP
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/local.config.ts
Labels: ns:xui-ao-webapp-pr-134

#140 Adding the missing APPINSIGHTS_INSTRUMENTATION key
  api/server.ts
Labels: ns:xui-ao-webapp-pr-140

#141 local to prod changes
  api/lib/config/environments/local.config.ts
Labels: ns:xui-ao-webapp-pr-141
