Repository hmcts/rpx-xui-approve-org, pull requests merged in 2019-10, with the labels that each got.

#159 Adding test for privacy policy
  src/app/components/privacy-policy/privacy-policy.component.spec.ts
Labels: ns:xui-ao-webapp-pr-159

#156 fixing the container width to 1220px
  src/app/components/accessibility/accessibility.component.html
  src/app/components/cookie-policy/cookie-policy.component.html
  src/app/components/privacy-policy/privacy-policy.component.html
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/assets/sass/components/_cookie-banner.scss
  src/org-manager/components/summary-pending/summary-pending.component.html
  src/org-manager/components/summary/summary.component.html
  src/org-manager/containers/org-pending-approve/org-pending-approve.component.html
  src/org-manager/containers/org-success/org-approval-success.component.html
  src/org-manager/containers/overview-pending/pending-overview.component.html
  src/shared/components/identity-bar/identity-bar.component.html
Labels: ns:xui-ao-webapp-pr-156

#146 EUI-371-changing pending org checkbox to radio - DO NOT MERGE
  src/org-manager/containers/overview-pending/pending-overview.component.html
  src/org-manager/containers/overview-pending/pending-overview.component.spec.ts
  src/org-manager/containers/overview-pending/pending-overview.component.ts
Labels: ns:xui-ao-webapp-pr-146

#162 http_changes_prd_config
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/local.config.ts
  api/lib/config/environments/prod.config.ts
Labels: ns:xui-ao-webapp-pr-162

#163 Remove deployment block
  Jenkinsfile_CNP
Labels: ns:xui-ao-webapp-pr-163

#165 enable-tls-flag
  api/lib/config/environments/demo.config.ts
  api/local.ts
  api/routes.ts
Labels: ns:xui-ao-webapp-pr-165

#173 Disable pact
  Jenkinsfile_CNP
Labels: ns:xui-ao-webapp-pr-173
