Repository hmcts/rpx-xui-approve-org, pull requests merged in 2019-06, with the labels that each got.

#28 EUI-143-build-pipeline-refactor
  Jenkinsfile_CNP
  api/server.ts
  charts/xui-approve-org/values.template.yaml
  config/application.config.ts
  config/environments/aat.config.ts
  config/environments/demo.config.ts
  config/environments/docker.config.ts
  config/environments/local.config.ts
  config/environments/mock.config.ts
  config/environments/preview.config.ts
  config/environments/prod.config.js
  config/environments/prod.config.ts
  config/environments/saat.config.ts
  config/environments/spreview.config.ts
  config/environments/sprod.config.ts
  config/index.ts
  docker/nginx.conf
  infrastructure/main.tf
  support/docker/buildrun-docker-base.sh
  support/docker/compose/docker-compose-ccd.yml
  support/docker/compose/docker-compose-dm.yml
  support/docker/compose/docker-compose-em.yml
  support/docker/compose/docker-compose-idam.yml
  support/docker/docker-compose-base-ports.yml
  support/docker/docker-compose-base.yml
Labels: ns:xui-approve-org-pr-28

#29 EUI-188 banner notification
  db.json
  package.json
  src/app/app.module.ts
  src/environments/environment.ts
  src/org-manager/containers/overview/org-overview.component.html
  src/org-manager/containers/overview/org-overview.component.ts
  src/org-pending/containers/overview/pending-overview.component.ts
  src/org-pending/services/pending-organisation.service.ts
  src/org-pending/store/actions/org-pending.actions.ts
  src/org-pending/store/reducers/org-pending.reducer.ts
  src/org-pending/store/selectors/org-pending.selectors.spec.ts
  src/org-pending/store/selectors/org-pending.selectors.ts
Labels: ns:xui-approve-org-pr-29

#31 Feature/eui 198 approve org aa
  angular.json
  db.json
  src/environments/environment.ts
  src/karma.conf.js
  src/org-manager/containers/overview/org-overview.component.html
  src/org-manager/containers/overview/org-overview.component.ts
  src/org-pending/config/pending-overview.config.ts
  src/org-pending/containers/index.ts
  src/org-pending/containers/org-pending-approve/org-pending-approve.component.html
  src/org-pending/containers/org-pending-approve/org-pending-approve.component.spec.ts
  src/org-pending/containers/org-pending-approve/org-pending-approve.component.ts
  src/org-pending/containers/overview/pending-overview.component.spec.ts
  src/org-pending/containers/overview/pending-overview.component.ts
  src/org-pending/mock/pending-organisation.mock.ts
  src/org-pending/org-pending.module.spec.ts
  src/org-pending/org-pending.ts
  src/org-pending/services/pending-organisation.service.spec.ts
  src/org-pending/services/pending-organisation.service.ts
  src/org-pending/store/actions/org-pending.actions.spec.ts
  src/org-pending/store/actions/org-pending.actions.ts
  src/org-pending/store/actions/single-org-pending.actions.spec.ts
  src/org-pending/store/effects/org-pending-effects.spec.ts
  src/org-pending/store/effects/org-pending.effects.ts
  src/org-pending/store/effects/single-org-pending.effects.spec.ts
  src/org-pending/store/reducers/org-pending.reducer.spec.ts
  src/org-pending/store/reducers/org-pending.reducer.ts
  src/org-pending/store/reducers/single-org-pending.reducer.spec.ts
  src/org-pending/store/selectors/org-pending.selectors.spec.ts
  src/org-pending/store/selectors/org-pending.selectors.ts
Labels: ns:xui-approve-org-pr-31

#34 Feature/eui 198 approve org aa
  .gitignore
  db.json_bkp
  package.json
  src/environments/environment.ts
  src/org-pending/containers/org-pending-approve/org-pending-approve.component.spec.ts
  src/org-pending/containers/org-pending-approve/org-pending-approve.component.ts
  src/org-pending/containers/org-success/org-approval-success.component.html
  src/org-pending/containers/overview/pending-overview.component.ts
  src/org-pending/mock/pending-organisation.mock.ts
  src/org-pending/services/pending-organisation.service.spec.ts
  src/org-pending/services/pending-organisation.service.ts
  src/org-pending/store/reducers/org-pending.reducer.ts
Labels: ns:xui-approve-org-pr-34

#32 Footer update
  sonar-project.properties
  src/app/app.constants.ts
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.spec.ts
  src/app/components/hmcts-global-footer/mock/hmcts-global-footer.mock.ts
  src/app/containers/footer/footer.component.spec.ts
  src/app/containers/footer/footer.component.ts
  src/assets/images/govuk-crest-2x.png
  src/assets/images/govuk-crest.png
Labels: ns:xui-ao-webapp-pr-32, ns:xui-approve-org-pr-32

#38 fixing header
  package.json
  src/app/app.routes.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/store/effects/app.effects.ts
  src/app/store/effects/index.ts
  src/app/store/reducers/index.ts
  src/custom-validators/checkboxes-be-checked.validator.ts
  src/environments/environment.prod.ts
  src/karma.conf.js
  src/org-pending/containers/org-pending-approve/org-pending-approve.component.spec.ts
  src/org-pending/containers/org-pending-summary/org-pending-summary.component.html
  src/org-pending/mock/pending-organisation.mock.ts
  src/org-pending/services/pending-organisation.service.ts
  src/org-pending/store/reducers/org-pending.reducer.spec.ts
  src/org-pending/store/selectors/org-pending.selectors.spec.ts
  src/users/components/index.ts
  src/users/components/invite-user-form/invite-user-form.component.html
  src/users/components/invite-user-form/invite-user-form.component.ts
  src/users/containers/index.ts
  src/users/containers/userform/user-form.component.html
  src/users/containers/userform/user-form.component.ts
  src/users/containers/users/users.component.html
  src/users/containers/users/users.component.ts
  src/users/models/userFrom.model.ts
  src/users/models/userform.model.ts
  src/users/services/index.ts
  src/users/services/invite-user.service.ts
  src/users/services/users.service.ts
  src/users/store/actions/index.ts
  src/users/store/actions/invite-user.actions.ts
  src/users/store/actions/user.actions.ts
  src/users/store/effects/index.ts
  src/users/store/effects/users.effects.ts
  src/users/store/index.ts
  src/users/store/reducers/index.ts
  src/users/store/reducers/invite-user.reducer.ts
  src/users/store/reducers/users.reducer.ts
  src/users/store/selectors/index.ts
  src/users/store/selectors/invite-user.selector.ts
  src/users/store/selectors/user.selectors.ts
  src/users/users.module.ts
  src/users/users.routing.ts
Labels: ns:xui-ao-webapp-pr-38

#41 EUI-301/Bug fix
  src/org-manager/components/notification-banner/notification-banner.component.html
  src/org-manager/containers/overview/org-overview.component.html
  src/org-manager/containers/overview/org-overview.component.ts
Labels: ns:xui-ao-webapp-pr-41

#42 automation framework and banner test added
  .gitignore
  package.json
  test/e2e/config/conf.js
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/config/protractor.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/approveOrganisationBanner.feature
  test/e2e/features/pageObjects/approveOrganisationObjects.js
  test/e2e/features/pageObjects/dummyObjects.steps.js
  test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
  test/e2e/features/step_definitions/steps/dummy.steps.js
  test/e2e/support/config.js
  test/e2e/support/constants.js
  test/e2e/support/hooks.js
  test/e2e/support/reports.js
  test/e2e/support/tagProcessor.js
  test/e2e/support/timeout.js
  test/e2e/support/world.js
  yarn.lock
Labels: ns:xui-ao-webapp-pr-42

#44 EUI-187-ApproveOrganisation
  test/e2e/features/app/confirmApproveOrganisation.feature
  test/e2e/features/pageObjects/approveOrganisationObjects.js
  test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
Labels: ns:xui-ao-webapp-pr-44

#45 EUI-309_bugfix_EUI-198_test_automation
  src/app/containers/header/header.component.ts
  test/e2e/config/conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/reviewApproveOrganisation.feature
  test/e2e/features/pageObjects/approveOrganisationObjects.js
  test/e2e/features/step_definitions/steps/reviewApproveOrganisation.steps.js
Labels: ns:xui-ao-webapp-pr-45

#46 Features/fz login redirect eui 178
  src/app/app.module.ts
  src/app/app.routes.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/models/configuration.model.ts
  src/org-manager/org-manager.routing.ts
  src/services/auth/auth.guard.spec.ts
  src/services/auth/auth.guard.ts
  src/services/auth/auth.service.spec.ts
  src/services/auth/auth.service.ts
Labels: ns:xui-ao-webapp-pr-46

#47 Whitelisting
  README.md
  package.json
  whitelist.sh
Labels: ns:xui-ao-webapp-pr-47

#50 routes are moved
  api/server.ts
Labels: ns:xui-ao-webapp-pr-50

#52 master test - 25-6-19
  README.md
  api/lib/appInsights.ts
  api/lib/config/application.config.ts
  api/lib/config/index.ts
  api/services/serviceAuth.ts
  config/index.ts
  tslint.json
Labels: ns:xui-ao-webapp-pr-52
