Repository hmcts/rpx-xui-approve-org, pull requests merged in 2019-12, with the labels that each got.

#188 Feature/eui 1157 google analytics
  package.json
  src/app/app.module.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  yarn.lock
Labels: ns:xui-ao-webapp-pr-188

#189 getenv package was removed?
  package.json
  yarn.lock
Labels: ns:xui-ao-webapp-pr-189

#198 Mark new and changed rules as warning only
  tslint.json
Labels: ns:xui-ao-webapp-pr-198

#197 Bug/eui 1280 hiding pba and bugs fz
  api/local.ts
  src/app/app.constants.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/karma.conf.js
  src/org-manager/containers/active-organisations/active-organisations.component.spec.ts
  src/org-manager/containers/approve-organisation-success/approve-organisation-success.component.spec.ts
  src/org-manager/containers/approve-organisation/approve-organisation.component.spec.ts
  src/org-manager/containers/organisation-details/organisation-details.component.html
  src/org-manager/models/organisation.ts
  src/org-manager/org-manager.routing.ts
  src/services/auth/auth.service.ts
Labels: ns:xui-ao-webapp-pr-197
