Repository hmcts/rpx-xui-approve-org, pull requests merged in 2019-07, with the labels that each got.

#58 update local config
  api/lib/config/environments/local.config.ts
Labels: ns:xui-ao-webapp-pr-58

#59 EUI-260 fixed issues around test and reverted .input in html
  src/org-manager/containers/org-pending-approve/org-pending-approve.component.html
  src/org-manager/containers/overview-pending/pending-overview.component.spec.ts
  src/org-manager/containers/overview-pending/pending-overview.component.ts
  src/org-manager/mock/pending-organisation.mock.ts
Labels: ns:xui-ao-webapp-pr-59

#60 EUI-361 fixed canactivate issue
  src/app/app.routes.ts
  src/org-manager/org-manager.routing.ts
Labels: ns:xui-ao-webapp-pr-60

#65 Feature/eui 247
  src/org-manager/components/summary/summary.component.html
  src/org-manager/components/summary/summary.component.spec.ts
  src/org-manager/components/summary/summary.component.ts
  src/org-manager/models/organisation.ts
  src/org-manager/store/effects/org-pending.effects.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/org-manager/store/selectors/organisation.selectors.spec.ts
  src/org-manager/store/selectors/organisation.selectors.ts
Labels: ns:xui-ao-webapp-pr-65

#69 Pending Organisation overview
  src/org-manager/components/summary-pending/summary-pending.component.html
  src/org-manager/components/summary-pending/summary-pending.component.spec.ts
  src/org-manager/components/summary-pending/summary-pending.component.ts
  src/org-manager/containers/overview-pending/pending-overview.component.ts
  src/org-manager/store/reducers/org-pending.reducer.ts
  src/org-manager/store/selectors/organisation.selectors.ts
Labels: ns:xui-ao-webapp-pr-69

#67 feature/EUI-47 logout on approve
  .gitignore
  angular.json
  api/auth/index.ts
  api/routes.ts
  api/server.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
  src/app/components/hmcts-global-header/hmcts-global-header.component.ts
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/containers/header/header.component.html
  src/app/containers/header/header.component.spec.ts
  src/app/containers/header/header.component.ts
  src/app/store/actions/app.actions.spec.ts
  src/app/store/actions/app.actions.ts
  src/app/store/actions/index.ts
  src/app/store/effects/app.effects.ts
  src/app/store/effects/index.ts
  src/app/store/reducers/app.reducer.ts
  src/karma.conf.js
  src/services/auth/auth.service.ts
Labels: ns:xui-ao-webapp-pr-67

#70 Eui 389 log inand log out automation
  test/e2e/config/conf.js
  test/e2e/features/app/approveOrganisationBanner.feature
  test/e2e/features/app/confirmApproveOrganisation.feature
  test/e2e/features/app/loginLogout.feature
  test/e2e/features/app/reviewApproveOrganisation.feature
  test/e2e/features/pageObjects/dummyObjects.steps.js
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/loginLogoutPage.js
  test/e2e/features/step_definitions/steps/dummy.steps.js
  test/e2e/features/step_definitions/steps/loginLogout.steps.js
Labels: ns:xui-ao-webapp-pr-70

#71 fixed typo EUI 436
  src/org-manager/components/summary-pending/summary-pending.component.html
  src/org-manager/components/summary/summary.component.html
Labels: ns:xui-ao-webapp-pr-71

#72 Feature/eui 169
  Jenkinsfile_CNP
  api/monitoring-tools/index.ts
  api/routes.ts
  package-lock.json
  package.json
  sonar-project.properties
  src/app/app.module.ts
  src/app/services/appInsightsWrapper.ts
  src/app/services/monitoring.service.spec.ts
  src/app/services/monitoring.service.ts
  yarn.lock
Labels: ns:xui-ao-webapp-pr-72

#73 EUI-213 added component
  src/app/containers/header/header.component.html
  src/shared/components/phase-banner/phase-banner.component.html
  src/shared/components/phase-banner/phase-banner.component.ts
  src/shared/shared.module.ts
Labels: ns:xui-ao-webapp-pr-73

#74 Feature/fz dynamic title eui 333
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/app/containers/app/app.component.html
  src/app/store/actions/app.actions.ts
  src/app/store/reducers/app.reducer.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
Labels: ns:xui-ao-webapp-pr-74

#75 Bug/cleaningup selectors
  api/routes.ts
  src/app/app.routes.ts
  src/app/containers/header/header.component.ts
  src/org-manager/components/summary-pending/summary-pending.component.ts
  src/org-manager/components/summary/summary.component.ts
  src/org-manager/containers/org-pending-approve/org-pending-approve.component.spec.ts
  src/org-manager/containers/org-pending-approve/org-pending-approve.component.ts
  src/org-manager/containers/overview-pending/pending-overview.component.ts
  src/org-manager/containers/overview/org-overview.component.html
  src/org-manager/org-manager.module.ts
  src/org-manager/store/reducers/index.ts
  src/org-manager/store/reducers/organisation.reducer.spec.ts
  src/org-manager/store/reducers/organisation.reducer.ts
  src/org-manager/store/reducers/single-org.reducer.spec.ts
  src/org-manager/store/selectors/index.ts
  src/org-manager/store/selectors/org-pending.selectors.spec.ts
  src/org-manager/store/selectors/org-pending.selectors.ts
  src/org-manager/store/selectors/organisation.selectors.spec.ts
  src/org-manager/store/selectors/organisation.selectors.ts
  src/org-manager/store/selectors/single-org-pending.selectors.spec.ts
  src/org-manager/store/selectors/single-org-pending.selectors.ts
  src/org-manager/store/selectors/single-org.selectors.spec.ts
  src/org-manager/store/selectors/single-org.selectors.ts
  test/e2e/features/step_definitions/steps/reviewApproveOrganisation.steps.js
Labels: ns:xui-ao-webapp-pr-75

#78 Feature/eui 311
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.ts
  src/org-manager/containers/overview-pending/pending-overview.component.html
  src/org-manager/containers/overview-pending/pending-overview.component.ts
  src/org-manager/store/actions/org-pending.actions.ts
  src/org-manager/store/reducers/org-pending.reducer.ts
  src/org-manager/store/selectors/org-pending.selectors.ts
Labels: ns:xui-ao-webapp-pr-78

#81 typo errors fixed EUI-440
  src/org-manager/containers/org-success/org-approval-success.component.html
  test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
Labels: ns:xui-ao-webapp-pr-81

#82 Approve organisation server error message
  src/org-manager/containers/org-pending-approve/org-pending-approve.component.html
  src/org-manager/containers/org-pending-approve/org-pending-approve.component.ts
  src/org-manager/containers/org-success/org-approval-success.component.html
  src/org-manager/containers/overview-pending/pending-overview.component.ts
  src/org-manager/store/actions/org-pending.actions.ts
  src/org-manager/store/effects/org-pending-effects.spec.ts
  src/org-manager/store/effects/org-pending.effects.ts
  src/org-manager/store/reducers/org-pending.reducer.ts
  test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
Labels: ns:xui-ao-webapp-pr-82

#79 undefined fix
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/org-manager/models/organisation.ts
  src/org-manager/services/pending-organisation.service.spec.ts
  src/org-manager/store/effects/org-pending.effects.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/org-manager/store/reducers/org-pending.reducer.ts
Labels: ns:xui-ao-webapp-pr-79

#83 EUI-368 Disable redux dev tools in prod
  src/app/app.module.ts
Labels: ns:xui-ao-webapp-pr-83

#84 Updating variable
  src/app/app.module.ts
Labels: ns:xui-ao-webapp-pr-84

#85 Feature/eui 398
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/org-manager/components/summary-pending/summary-pending.component.html
  src/org-manager/components/summary/summary.component.html
  src/org-manager/containers/org-pending-approve/org-pending-approve.component.html
  src/org-manager/containers/overview-pending/pending-overview.component.html
  src/org-manager/containers/overview-pending/pending-overview.component.spec.ts
  src/org-manager/containers/overview-pending/pending-overview.component.ts
  src/org-manager/containers/overview/org-overview.component.html
  src/org-manager/containers/overview/org-overview.component.ts
  src/org-manager/mock/pending-organisation.mock.ts
  src/org-manager/models/organisation.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/org-manager/store/reducers/organisation.reducer.spec.ts
Labels: ns:xui-ao-webapp-pr-85

#87 Feature/eui 463
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/services/logger.service.spec.ts
  src/app/services/logger.service.ts
  yarn.lock
Labels: ns:xui-ao-webapp-pr-87

#88 url redirect adding scope
  src/services/auth/auth.service.ts
Labels: ns:xui-ao-webapp-pr-88

#89 Feature/eui 452 shuttering aa
  api/healthCheck/index.ts
  api/lib/config/environments/aat.config.ts
  api/lib/config/environments/demo.config.ts
  api/lib/config/environments/docker.config.ts
  api/lib/config/environments/laat.config.ts
  api/lib/config/environments/ldocker.config.ts
  api/lib/config/environments/local.config.ts
  api/lib/config/environments/mock.config.ts
  api/lib/config/environments/preview.config.ts
  api/lib/config/environments/prod.config.ts
  api/lib/config/environments/saat.config.ts
  api/lib/config/environments/spreview.config.ts
  api/lib/config/environments/sprod.config.ts
  api/routes.ts
  src/app/containers/index.ts
  src/app/containers/service-down/service-down.component.html
  src/app/containers/service-down/service-down.component.ts
  src/app/store/reducers/index.ts
  src/shared/guards/health-check.guard.spec.ts
  src/shared/guards/health-check.guard.ts
  src/shared/services/health-check.service.spec.ts
  src/shared/services/health-check.service.ts
  src/shared/shared.module.ts
  tslint.json
Labels: ns:xui-ao-webapp-pr-89
