Repository hmcts/rpx-xui-approve-org, pull requests merged in 2019-09, with the labels that each got.

#142 add extra roles
  api/auth/index.ts
  src/services/auth/auth.service.ts
Labels: ns:xui-ao-webapp-pr-142

#143 AO-Configuration cleanup to support multiple environment- pr, demo an…
  api/lib/config/environments/local.config.ts
  src/app/app.constants.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/services/auth/auth.service.ts
Labels: ns:xui-ao-webapp-pr-143

#147 Adding logging for Appinsights not working
  api/lib/appInsights.ts
  api/lib/log4jui.ts
  api/local.ts
Labels: ns:xui-ao-webapp-pr-147

#148 Incorrect environment variable PUI_ENV
  api/lib/appInsights.ts
Labels: ns:xui-ao-webapp-pr-148

#150 update s2s protocol to http
  api/lib/config/environments/laat.config.ts
  api/lib/config/environments/mock.config.ts
  api/lib/config/environments/preview.config.ts
  api/lib/config/environments/prod.config.ts
  api/lib/config/environments/saat.config.ts
  api/lib/config/environments/spreview.config.ts
  api/lib/config/environments/sprod.config.ts
  config/environments/aat.config.ts
  config/environments/local.config.ts
  config/environments/preview.config.ts
  config/environments/prod.config.ts
Labels: ns:xui-ao-webapp-pr-150

#145 upgrade to the latest govuk/frontend - DO NOT MERGE
  package.json
  src/app/components/hmcts-global-header/hmcts-global-header.component.html
  src/assets/components/button/_button.scss
  src/assets/components/case-actions/_case-actions.scss
  src/assets/components/casefile/_casefile-2.scss
  src/assets/components/casefile/_casefile-3.scss
  src/assets/components/casefile/_casefile.scss
  src/assets/components/tabs/_tabs.scss
  src/assets/components/tree/_tree.scss
  src/assets/sass/application.scss
  src/assets/sass/patterns/_pba.scss
  src/styles.scss
  yarn.lock
Labels: ns:xui-ao-webapp-pr-145

#149 changing pending badge from green to blue
  src/org-manager/components/summary-pending/summary-pending.component.html
Labels: ns:xui-ao-webapp-pr-149

#153 fixing for EUI-622-back-button & EUI-579-update-title
  src/org-manager/components/back-link/back-link.component.html
  src/org-manager/components/back-link/back-link.component.spec.ts
  src/org-manager/components/back-link/back-link.component.ts
  src/org-manager/components/index.ts
  src/org-manager/components/summary-pending/summary-pending.component.html
  src/org-manager/components/summary-pending/summary-pending.component.ts
  src/org-manager/components/summary/summary.component.html
  src/org-manager/components/summary/summary.component.ts
  src/org-manager/containers/org-pending-approve/org-pending-approve.component.html
  src/org-manager/containers/org-pending-approve/org-pending-approve.component.spec.ts
  src/org-manager/containers/org-pending-approve/org-pending-approve.component.ts
  src/org-manager/containers/overview-pending/pending-overview.component.html
  src/org-manager/containers/overview-pending/pending-overview.component.ts
Labels: ns:xui-ao-webapp-pr-153

#157 adding feedback link
  src/shared/components/phase-banner/phase-banner.component.html
Labels: ns:xui-ao-webapp-pr-157
