Repository hmcts/rpx-xui-approve-org, pull requests merged in 2019-11, with the labels that each got.

#174 Enable PR envs
  Dockerfile
  api/lib/config/environments/preview.config.ts
  api/local.ts
  api/routes.ts
  charts/xui-ao-webapp/values.aat.template.yaml
  charts/xui-ao-webapp/values.preview.template.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
  whitelist.sh
Labels: ns:xui-ao-webapp-pr-174

#175 seperate s2s & idam to different KV secret
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  charts/xui-ao-webapp/values.yaml
  infrastructure/main.tf
Labels: ns:xui-ao-webapp-pr-175

#176 fixed terraform variables
  infrastructure/variables.tf
Labels: ns:xui-ao-webapp-pr-176

#178 fixed terraform variables
  infrastructure/variables.tf
Labels: ns:xui-ao-webapp-pr-178

#179 added logging for debug
  api/lib/environment.config.ts
  api/lib/tunnel.ts
  api/server.ts
Labels: ns:xui-ao-webapp-pr-179

#181 fixed app port
  api/.env.defaults
  api/interfaces/environment.config.ts
  api/lib/environment.config.ts
  api/lib/tunnel.ts
  api/local.ts
  api/server.ts
  infrastructure/aat.tfvars
  infrastructure/variables.tf
  src/models/environmentConfig.model.ts
Labels: ns:xui-ao-webapp-pr-181

#183 making both date the same
  src/app/components/accessibility/accessibility.component.html
  src/app/components/accessibility/accessibility.component.ts
Labels: CABApproved, ns:xui-ao-webapp-pr-183

#172 Enable live stream in App Insights - AO
  api/lib/appInsights.ts
  package.json
  yarn.lock
Labels: CABApproved, ns:xui-ao-webapp-pr-172

#186 upgarde helm client version
  Jenkinsfile_CNP
  charts/xui-ao-webapp/Chart.yaml
Labels: ns:xui-ao-webapp-pr-186
