Repository hmcts/rpx-xui-approve-org, pull requests merged in 2020-09, with the labels that each got.

#395 EUI-2515: Fix page content for deleting an "Active" organisation
  src/org-manager/containers/delete-organisation-success/delete-organisation-success.component.html
  src/org-manager/containers/delete-organisation/delete-organisation.component.html
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-395

#393 crossbrowser_fix
  api/application.ts
  api/environment/index.ts
  api/yarn.lock
  infrastructure/state.tf
  package.json
  test/e2e/config/crossbrowser.conf.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-393

#402 EUI_2572_2578_NightlyFixes
  audit.json
  security.sh
  test/e2e/config/crossbrowser.conf.js
  test/e2e/features/step_definitions/steps/loginLogout.steps.js
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-402

#405 tests/hooks async attach screenshot fix.
  Jenkinsfile_nightly
  security.sh
  test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
  test/e2e/features/step_definitions/steps/loginLogout.steps.js
  test/e2e/support/CucumberReporter.js
  test/e2e/support/customWaits.js
  test/e2e/support/hooks.js
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-405

#406 EUI-2625-accessibility-policy
  api/configuration/ui.ts
  charts/xui-ao-webapp/values.preview.template.yaml
  package.json
  src/app/components/accessibility/accessibility.component.html
  src/app/components/accessibility/accessibility.component.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-406

#407 Security exceptions audit json
  Jenkinsfile_nightly
  audit.json
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-407
