Repository hmcts/rpx-xui-approve-org, pull requests merged in 2020-03, with the labels that each got.

#259 fixing functional tests
  package.json
  test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
  test/e2e/support/constants.js
Labels: ns:xui, rel:xui-ao-webapp-pr-259

#256 feature toggle implementation via config
  api/configuration/index.ts
  api/configuration/references.ts
  api/configuration/ui.ts
  api/lib/appInsights.ts
  api/lib/tunnel.ts
  api/local.ts
  api/server.ts
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/values.preview.template.yaml
  charts/xui-ao-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
Labels: ns:xui, rel:xui-ao-webapp-pr-256

#253 Feature/eui 1586 helmet security
  api/configuration/constants.ts
  api/configuration/references.ts
  api/local.ts
  api/server.ts
  api/webpack-node.config.js
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/requirements.yaml
  charts/xui-ao-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-ao-webapp-pr-253

#262 Update ITHC IDAM url
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/values.yaml
Labels: ns:xui, rel:xui-ao-webapp-pr-262

#264 added health endpoint
  api/health.ts
  api/local.ts
  api/server.ts
Labels: ns:xui, rel:xui-ao-webapp-pr-264

#266 Deploy develop-master
  api/health.ts
  api/local.ts
  api/server.ts
Labels: ns:xui, rel:xui-ao-webapp-pr-266

#235 Feature/eui 1355 adding users
  api/organisation/index.ts
  package.json
  src/app/app.constants.ts
  src/app/components/privacy-policy/privacy-policy.component.spec.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/org-manager/components/index.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/components/organisation-details-info/organisation-details-info.component.spec.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.ts
  src/org-manager/containers/edit-details/edit-details.component.html
  src/org-manager/containers/organisation-details/organisation-details.component.html
  src/org-manager/containers/organisation-details/organisation-details.component.spec.ts
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/mock/pending-organisation.mock.ts
  src/org-manager/models/organisation.ts
  src/org-manager/services/organisation.service.spec.ts
  src/org-manager/services/organisation.service.ts
  src/org-manager/services/pba-account-details.service.spec.ts
  src/org-manager/services/pba-account-details.services.ts
  src/org-manager/services/pending-organisation.service.spec.ts
  src/org-manager/services/pending-organisation.service.ts
  src/org-manager/services/update-pba.service.spec.ts
  src/org-manager/services/update-pba.services.ts
  src/org-manager/store/actions/organisations.actions.spec.ts
  src/org-manager/store/actions/organisations.actions.ts
  src/org-manager/store/effects/organisation-effects.spec.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/org-manager/store/reducers/organisation.reducer.spec.ts
  src/org-manager/store/reducers/organisation.reducer.ts
  src/org-manager/store/selectors/organisation.selectors.spec.ts
  src/org-manager/store/selectors/organisation.selectors.ts
  yarn.lock
Labels: ns:xui, rel:xui-ao-webapp-pr-235

#221 update new content for accessibility and terms and conditions
  src/app/components/accessibility/accessibility.component.html
  src/app/components/accessibility/accessibility.component.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
Labels: ns:xui, rel:xui-ao-webapp-pr-221

#267 DEVELOP TO MASTER
  api/organisation/index.ts
  api/webpack-node.config.js
  package.json
  src/app/app.constants.ts
  src/app/components/accessibility/accessibility.component.html
  src/app/components/accessibility/accessibility.component.ts
  src/app/components/privacy-policy/privacy-policy.component.spec.ts
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/org-manager/components/index.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/components/organisation-details-info/organisation-details-info.component.spec.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.ts
  src/org-manager/containers/edit-details/edit-details.component.html
  src/org-manager/containers/organisation-details/organisation-details.component.html
  src/org-manager/containers/organisation-details/organisation-details.component.spec.ts
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/mock/pending-organisation.mock.ts
  src/org-manager/models/organisation.ts
  src/org-manager/services/organisation.service.spec.ts
  src/org-manager/services/organisation.service.ts
  src/org-manager/services/pba-account-details.service.spec.ts
  src/org-manager/services/pba-account-details.services.ts
  src/org-manager/services/pending-organisation.service.spec.ts
  src/org-manager/services/pending-organisation.service.ts
  src/org-manager/services/update-pba.service.spec.ts
  src/org-manager/services/update-pba.services.ts
  src/org-manager/store/actions/organisations.actions.spec.ts
  src/org-manager/store/actions/organisations.actions.ts
  src/org-manager/store/effects/organisation-effects.spec.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/org-manager/store/reducers/organisation.reducer.spec.ts
  src/org-manager/store/reducers/organisation.reducer.ts
  src/org-manager/store/selectors/organisation.selectors.spec.ts
  src/org-manager/store/selectors/organisation.selectors.ts
  yarn.lock
Labels: ns:xui, rel:xui-ao-webapp-pr-267

#269 Master to develop
  api/.env.defaults
  charts/xui-ao-webapp/Chart.yaml
  package.json
  test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
  test/e2e/features/step_definitions/steps/loginLogout.steps.js
Labels: ns:xui, rel:xui-ao-webapp-pr-269

#271 Functions test merged from master for missing changes
  src/org-manager/containers/approve-organisation/approve-organisation.component.html
  test/e2e/config/conf.js
  test/e2e/features/app/approveOrganisationBanner.feature
  test/e2e/features/app/confirmApproveOrganisation.feature
  test/e2e/features/app/reviewApproveOrganisation.feature
  test/e2e/features/pageObjects/approveOrganisationObjects.js
  test/e2e/features/pageObjects/organisationListPage.js
  test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
  test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
  test/e2e/features/step_definitions/steps/loginLogout.steps.js
  test/e2e/features/step_definitions/steps/searchOrganisations.steps.js
  test/e2e/support/customWaits.js
Labels: ns:xui, rel:xui-ao-webapp-pr-271

#275 add redis infra for AO
  api/application.ts
  api/configuration/references.ts
  api/lib/sessionStore.ts
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/requirements.yaml
  charts/xui-ao-webapp/values.preview.template.yaml
  charts/xui-ao-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-ao-webapp-pr-275

#279 updating IDAM URLS to non AKS
  infrastructure/ithc.tfvars
Labels: ns:xui, rel:xui-ao-webapp-pr-279

#287 Redis changes and application.ts refactoring
  Jenkinsfile_CNP
  README.md
  api/application.ts
  api/auth/index.ts
  api/auth/serviceToken.ts
  api/configuration/health.ts
  api/configuration/references.ts
  api/configuration/ui.ts
  api/lib/errorStack.ts
  api/lib/models/index.ts
  api/lib/sessionStore.ts
  api/lib/stateEngine.ts
  api/local.ts
  api/package.json
  api/routes.ts
  api/server.ts
  api/states/mapping.ts
  api/states/templates/emailAddress.ts
  api/states/templates/index.ts
  api/states/templates/name.ts
  api/states/templates/organisationAddress.ts
  api/states/templates/organisationDx.ts
  api/states/templates/organisationHaveDx.ts
  api/states/templates/organisationName.ts
  api/states/templates/organisationPba.ts
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/requirements.yaml
  charts/xui-ao-webapp/values.preview.template.yaml
  charts/xui-ao-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  src/environments/environment.prod.ts
  yarn.lock
Labels: ns:xui, rel:xui-ao-webapp-pr-287

#291 Application.ts with api/auth changes
  README.md
  api/application.ts
  api/auth/index.ts
  api/auth/userRoleAuth.ts
  api/configuration/constants.ts
  api/configuration/index.ts
  api/lib/models/index.ts
  api/lib/objectUtilities.ts
  package.json
  src/services/auth/auth.service.ts
  yarn.lock
Labels: ns:xui, rel:xui-ao-webapp-pr-291

#292 Develop to master Login issue fix
  README.md
  api/application.ts
  api/auth/index.ts
  api/auth/userRoleAuth.ts
  api/configuration/constants.ts
  api/configuration/index.ts
  api/lib/models/index.ts
  api/lib/objectUtilities.ts
  package.json
  src/services/auth/auth.service.ts
  yarn.lock
Labels: ns:xui, rel:xui-ao-webapp-pr-292

#299 removing APP_INSIGHTS_KEY
  api/application.ts
Labels: ns:xui, rel:xui-ao-webapp-pr-299

#300 Adding the application and session with health check
  api/application.ts
  api/lib/sessionStore.ts
  package.json
  yarn.lock
Labels: ns:xui, rel:xui-ao-webapp-pr-300
