Repository hmcts/rpx-xui-approve-org, pull requests merged in 2020-01, with the labels that each got.

#203 adding pba code in
  src/org-manager/containers/organisation-details/organisation-details.component.html
  src/org-manager/org-manager.routing.ts
Labels: ns:xui, rel:xui-ao-webapp-pr-203

#199 Feature/eui 1014 / EUI-1274 Search organisations
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/org-manager/containers/active-organisations/active-organisations.component.html
  src/org-manager/containers/active-organisations/active-organisations.component.spec.ts
  src/org-manager/containers/active-organisations/active-organisations.component.ts
  src/org-manager/containers/index.ts
  src/org-manager/containers/pending-organisations/pending-organisations.component.html
  src/org-manager/containers/pending-organisations/pending-organisations.component.spec.ts
  src/org-manager/containers/pending-organisations/pending-organisations.component.ts
  src/org-manager/containers/search-organisations-form/search-organisations-form.component.html
  src/org-manager/containers/search-organisations-form/search-organisations-form.component.scss
  src/org-manager/containers/search-organisations-form/search-organisations-form.component.spec.ts
  src/org-manager/containers/search-organisations-form/search-organisations-form.component.ts
  src/org-manager/mock/pending-organisation.mock.ts
  src/org-manager/org-manager.module.ts
  src/org-manager/pipes/filter-organisations.pipe.spec.ts
  src/org-manager/pipes/filter-organisations.pipe.ts
  src/org-manager/pipes/index.ts
  src/org-manager/services/pending-organisation.service.spec.ts
  src/org-manager/store/selectors/organisation.selectors.ts
Labels: ns:xui, ns:xui-ao-webapp-pr-199, rel:xui-ao-webapp-pr-199

#204 making pending organisation page as default instead of active organis…
  package.json
  src/org-manager/containers/active-organisations/active-organisations.component.html
  src/org-manager/containers/active-organisations/active-organisations.component.spec.ts
  src/org-manager/containers/active-organisations/active-organisations.component.ts
  src/org-manager/containers/pending-organisations/pending-organisations.component.html
  src/org-manager/containers/pending-organisations/pending-organisations.component.spec.ts
  src/org-manager/containers/pending-organisations/pending-organisations.component.ts
  src/org-manager/org-manager.routing.ts
  src/org-manager/store/selectors/organisation.selectors.ts
  test/e2e/config/conf.js
  test/e2e/features/app/approveOrganisationBanner.feature
  test/e2e/features/app/confirmApproveOrganisation.feature
  test/e2e/features/app/reviewApproveOrganisation.feature
  test/e2e/features/pageObjects/approveOrganisationObjects.js
  test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
  test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
  test/e2e/features/step_definitions/steps/loginLogout.steps.js
  test/e2e/support/customWaits.js
Labels: ns:xui, rel:xui-ao-webapp-pr-204

#206 remove the gov-ui library and integrate with common lib gov ui
  package.json
  projects/gov-ui/src/lib/components/gov-uk-checkbox/gov-uk-checkbox.component.html
  projects/gov-ui/src/lib/components/gov-uk-checkbox/gov-uk-checkbox.component.ts
  projects/gov-ui/src/lib/components/gov-uk-error-message/gov-uk-error-message.component.ts
  projects/gov-ui/src/lib/components/gov-uk-error-summary/gov-uk-error-summary.component.ts
  projects/gov-ui/src/lib/components/gov-uk-form-group-wrapper/gov-uk-form-group-wrapper.component.ts
  projects/gov-ui/src/lib/components/gov-uk-input/gov-uk-input.component.ts
  projects/gov-ui/src/lib/components/gov-uk-label/gov-uk-label.component.ts
  projects/gov-ui/src/lib/components/gov-uk-main-wrapper/gov-uk-main-wrapper.component.ts
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.html
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.scss
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.spec.ts
  projects/gov-ui/src/lib/components/govuk-table/govuk-table.component.ts
  projects/gov-ui/src/lib/components/hmcts-banner/hmcts-banner.component.ts
  projects/gov-ui/src/lib/components/hmcts-error-summary/hmcts-error-summary.component.ts
  projects/gov-ui/src/lib/components/hmcts-identity-bar/hmcts-identity-bar.component.html
  projects/gov-ui/src/lib/components/hmcts-identity-bar/hmcts-identity-bar.component.scss
  projects/gov-ui/src/lib/components/hmcts-identity-bar/hmcts-identity-bar.component.ts
  projects/gov-ui/src/lib/components/hmcts-primary-navigation/hmcts-primary-navigation.component.html
  projects/gov-ui/src/lib/components/hmcts-primary-navigation/hmcts-primary-navigation.component.scss
  projects/gov-ui/src/lib/components/hmcts-primary-navigation/hmcts-primary-navigation.component.spec.ts
  projects/gov-ui/src/lib/components/hmcts-primary-navigation/hmcts-primary-navigation.component.ts
  projects/gov-ui/src/lib/components/hmcts-sub-navigation/hmcts-sub-navigation.component.html
  projects/gov-ui/src/lib/components/hmcts-sub-navigation/hmcts-sub-navigation.component.scss
  projects/gov-ui/src/lib/components/hmcts-sub-navigation/hmcts-sub-navigation.component.ts
  projects/gov-ui/src/lib/gov-ui.module.ts
  src/app/app.module.ts
  src/app/components/index.ts
  src/app/containers/header/header.component.html
  src/org-manager/containers/edit-details/edit-details.component.html
  src/org-manager/containers/edit-details/edit-details.component.ts
  src/org-manager/containers/index.ts
  src/org-manager/containers/organisation-details/organisation-details.component.html
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/containers/pending-organisations/pending-organisations.component.html
  src/org-manager/containers/pending-organisations/pending-organisations.component.ts
  src/org-manager/containers/search-organisations-form/search-organisations-form.component.html
  src/org-manager/containers/search-organisations-form/search-organisations-form.component.spec.ts
  src/org-manager/org-manager.module.ts
  src/org-manager/services/pending-organisation.service.spec.ts
  src/shared/shared.module.ts
  yarn.lock
Labels: ns:xui, rel:xui-ao-webapp-pr-206

#210 work for EUI-1372, EUI-1412 and EUI-1415
  src/org-manager/containers/active-organisations/active-organisations.component.html
  src/org-manager/containers/organisation-details/organisation-details.component.html
  src/org-manager/containers/organisation-details/organisation-details.component.spec.ts
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/containers/pending-organisations/pending-organisations.component.html
  src/org-manager/containers/pending-organisations/pending-organisations.component.ts
  src/org-manager/store/effects/organisation-effects.spec.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/org-manager/store/reducers/organisation.reducer.spec.ts
  src/org-manager/store/reducers/organisation.reducer.ts
  test/e2e/features/app/confirmApproveOrganisation.feature
  test/e2e/features/app/search.feature
  test/e2e/features/pageObjects/organisationListPage.js
  test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
  test/e2e/features/step_definitions/steps/searchOrganisations.steps.js
  test/e2e/support/customWaits.js
Labels: ns:xui, rel:xui-ao-webapp-pr-210
