Repository hmcts/rpx-xui-approve-org, pull requests merged in 2020-07, with the labels that each got.

#349 update terraform
  .github/stale.yml
  Jenkinsfile_CNP
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-349

#357 latest library version to fix/tidy up auth event callback and roles regex passed in
  .gitignore
  api/application.ts
  api/auth/index.ts
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-357

#363 add app insghts
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-363

#366 update node dependencies for CVE scanning
  package-lock.json
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-366

#368 Fix to handle EUI-1856 login.
  test/e2e/features/pageObjects/organisationListPage.js
  test/e2e/features/step_definitions/steps/loginLogout.steps.js
Labels: ns:xui, prd:xui, qa/automation, rel:xui-ao-webapp-pr-368

#367 update node dependencies for CVE scanning (#366)
  Jenkinsfile_CNP
  package-lock.json
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-367
