Repository hmcts/rpx-xui-approve-org, pull requests merged in 2020-06, with the labels that each got.

#328 Update privacy policy with latest version
  src/app/components/privacy-policy/privacy-policy.component.html
  src/app/components/privacy-policy/privacy-policy.component.ts
Labels: ns:xui, rel:xui-ao-webapp-pr-328

#332 Nightly tests and report fix
  test/e2e/config/fullfunctional.conf.js
  test/e2e/features/app/reviewApproveOrganisation.feature
Labels: ns:xui, rel:xui-ao-webapp-pr-332

#333 EUI-2055 pa11y tests implementation
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package-lock.json
  package.json
  test/accessibility/config/config.js
  test/accessibility/helpers/applicationActions.js
  test/accessibility/helpers/pa11yUtil.js
  test/accessibility/helpers/pallyActions.js
  test/accessibility/reporter/Report.html
  test/accessibility/reporter/customReporter.js
  test/accessibility/reporter/resources/angular.min.js
  test/accessibility/reporter/resources/css/all.css
  test/accessibility/reporter/resources/webfonts/fa-solid-900.woff2
  test/accessibility/tests/index.js
  test/e2e/config/fullfunctional.conf.js
  yarn.lock
Labels: ns:xui, rel:xui-ao-webapp-pr-333

#339 fixed missing stryker config file.
  stryker.node.conf.js
Labels: ns:xui, rel:xui-ao-webapp-pr-339

#341 EUI-2081: Timeout modal dialog styling change
  package.json
  src/app/components/signed-out/signed-out.component.html
  src/app/containers/app/app.component.html
  src/styles.scss
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-341

#344 fix new preview
  charts/xui-ao-webapp/values.preview.template.yaml
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-344

#342 Feature/auth middleware pipeline callback url
  api/application.ts
  api/auth/index.ts
  api/auth/serviceToken.ts
  api/environment/index.ts
  api/keepalive/index.ts
  api/lib/appInsights.ts
  api/lib/errorStack.ts
  api/lib/http.ts
  api/lib/interceptors.ts
  api/lib/log4jui.ts
  api/lib/models/index.ts
  api/lib/models/templates.ts
  api/lib/models/transactions.ts
  api/lib/sessionStore.ts
  api/middleware/auth.ts
  api/routes.ts
  api/server.ts
  api/user/index.ts
  charts/xui-ao-webapp/values.preview.template.yaml
  package.json
  src/app/app-initilizer.spec.ts
  src/app/app-initilizer.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/signed-out/signed-out.component.html
  src/app/containers/app/app.component.html
  src/app/containers/header/header.component.spec.ts
  src/app/containers/header/header.component.ts
  src/app/services/keep-alive/keep-alive.service.ts
  src/app/services/logger.service.ts
  src/app/store/effects/app.effects.ts
  src/services/auth/auth.service.ts
  src/styles.scss
  stryker.log
  test/e2e/features/pageObjects/loginLogoutObjects.js
  test/e2e/features/step_definitions/steps/loginLogout.steps.js
  test/e2e/support/customWaits.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-342

#345 bug to fix the users/Organisation state
  src/org-manager/containers/organisation-details/organisation-details.component.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-345

#346 add stalebot for AO
  .github/stale.yml
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-346
