Repository hmcts/rpx-xui-approve-org, pull requests merged in 2021-06, with the labels that each got.

#491 crossbrowser fix for AO
  package.json
  test/e2e/config/crossbrowser.conf.js
  test/e2e/features/app/search.feature
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-491

#494 Add IDAM whitelist
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/values.preview.template.yaml
  charts/xui-ao-webapp/values.yaml
  package.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-494

#464 feature/EUI-3407 - zap security configuration
  api/application.ts
  audit.json
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-464

#497 CVEs fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-497

#498 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-498

#500 EUI-4246: Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-500
