Repository hmcts/rpx-xui-approve-org, pull requests merged in 2021-12, with the labels that each got.

#545 Upgrade properties-volume
  package.json
  test/data/Staff Data Upload Template V2.0.0.xlsx
  test/data/~$Staff Data Upload Template V2.0.0.xlsx
  test/e2e/features/step_definitions/steps/staffDetails.steps.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-545

#546 Update known issue list
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-546

#547 Upgrade node-gyp
  .nvmrc
  README.md
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-547

#548 a11y test retry on error
  test/accessibility/config/protractor.conf.js
  test/accessibility/helpers/pa11yUtil.js
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-548
