Repository hmcts/rpx-xui-approve-org, pull requests merged in 2021-01, with the labels that each got.

#433 Release/cve and dynamic menu
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  api/application.ts
  api/configuration/references.ts
  api/configuration/ui.ts
  api/interfaces/ui.config.ts
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/requirements.yaml
  charts/xui-ao-webapp/values.preview.template.yaml
  charts/xui-ao-webapp/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/containers/header/header.component.html
  src/app/containers/header/header.component.spec.ts
  src/app/containers/header/header.component.ts
  src/app/containers/hmcts-primary-navigation/hmcts-primary-navigation.component.html
  src/app/containers/hmcts-primary-navigation/hmcts-primary-navigation.component.scss
  src/app/containers/hmcts-primary-navigation/hmcts-primary-navigation.component.spec.ts
  src/app/containers/hmcts-primary-navigation/hmcts-primary-navigation.component.ts
  src/app/containers/index.ts
  src/app/containers/redirect/redirect.component.spec.ts
  src/app/containers/redirect/redirect.component.ts
  src/app/store/reducers/index.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/main.ts
  src/models/environmentConfig.model.ts
  src/org-manager/org-manager.routing.ts
  test/accessibility/helpers/pa11yUtil.js
  test/accessibility/tests/activeOrgUsersTab.js
  test/accessibility/tests/deleteOrg.js
  test/accessibility/tests/footerPages.js
  test/accessibility/tests/orgUpdateApprove.js
  test/e2e/features/pageObjects/headerPage.js
  test/e2e/features/pageObjects/loginLogoutObjects.js
  test/e2e/features/pageObjects/organisationPage.js
  test/e2e/support/CucumberReporter.js
  test/e2e/support/hooks.js
  test/ngIntegration/config/protractor.conf.js
  test/ngIntegration/tests/headerTabs.test.js
  test/ngIntegration/util/browserUtil.js
  test/nodeMock/app.js
  test/nodeMock/mockdata/appConfig.js
  test/nodeMock/reqResMapping.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-433

#427 API Functional Tests EUI-1592
  Jenkinsfile_CNP
  package.json
  test/e2e/features/app/confirmApproveOrganisation.feature
  test/integration/config/application.config.ts
  test/integration/config/environments/aat.config.ts
  test/integration/config/environments/demo.config.ts
  test/integration/config/environments/docker.config.ts
  test/integration/config/environments/ithc.config.ts
  test/integration/config/environments/ldocker.config.ts
  test/integration/config/environments/local.config.ts
  test/integration/config/environments/mock.config.ts
  test/integration/config/environments/preview.config.ts
  test/integration/config/environments/prod.config.ts
  test/integration/config/environments/saat.config.ts
  test/integration/config/environments/spreview.config.ts
  test/integration/config/environments/sprod.config.ts
  test/integration/config/index.ts
  test/integration/tests/Approve_Pending_Organisations.ts
  test/integration/tests/Delete_Active_Organisations.ts
  test/integration/tests/Delete_Pending_Organisations.ts
  test/integration/tests/get_Active_Organisations.ts
  test/integration/tests/get_Organisation_User_Details.ts
  test/integration/tests/get_PBA_Account_names.ts
  test/integration/tests/get_Pending_Organisations.ts
  test/integration/tests/post_Invite_User.ts
  test/integration/tests/post_Update_PBA.ts
  test/integration/tests/test.ts
  test/integration/tests/utils/generateAPI.ts
  test/integration/tests/utils/generatePOSTAPI.ts
  test/integration/tests/utils/generateregPOSTAPI.ts
  test/integration/tests/utils/getCookie.ts
  test/integration/tests/utils/getToken.ts
  test/integration/tests/utils/index.ts
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-427

#439 Ao api functional tests e UI 1592
  test/integration/tests/Approve_Pending_Organisations.ts
  test/integration/tests/Delete_Active_Organisations.ts
  test/integration/tests/Delete_Pending_Organisations.ts
  test/integration/tests/get_Active_Organisations.ts
  test/integration/tests/get_Organisation_User_Details.ts
  test/integration/tests/get_PBA_Account_names.ts
  test/integration/tests/get_Pending_Organisations.ts
  test/integration/tests/post_Invite_User.ts
  test/integration/tests/post_Update_PBA.ts
  test/integration/tests/utils/getCookie.ts
  test/integration/tests/utils/index.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-439

#443 Infra upgrade
  Jenkinsfile_nightly
  README.md
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/requirements.yaml
  charts/xui-ao-webapp/values.yaml
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
  test/e2e/features/app/organisationUserReadAccess.feature
Labels: ns:xui, pinned, prd:xui, rel:xui-ao-webapp-pr-443

#442 Update postal and email address in Privacy policy
  src/app/components/privacy-policy/privacy-policy.component.html
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-442
