Repository hmcts/rpx-xui-approve-org, pull requests merged in 2021-04, with the labels that each got.

#470 Xui cve fix
  README.md
  package.json
  test/e2e/config/conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/features/app/staffDetails.feature
  test/e2e/features/step_definitions/steps/loginLogout.steps.js
  test/integration/tests/utils/getCookie.ts
  test/ngIntegration/stepDefinitions/staffDetails.steps.js
  whitelist.sh
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-470

#476 Security check issue: jose
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-476

#473 Build Upgrade
  .dockerignore
  Jenkinsfile_CNP
  README.md
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/values.preview.template.yaml
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-473

#477 Xui disable autoscaling
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/values.yaml
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-477

#468 Ta-229: Fix failing RD and Idam Pact test
  Jenkinsfile_CNP
  api/test/pact/pact-tests/idam/getUserDetails.spec.ts
  api/test/pact/pact-tests/rdProfessional/getOrganisations.spec.ts
  package.json
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-468

#479 Geckocide
  package.json
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-479
