Repository hmcts/rpx-xui-approve-org, pull requests merged in 2021-11, with the labels that each got.

#526 cve-supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-526

#472 EUI-2133 Non-descriptive Headings
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-472

#478 EUI-2135 imported latest gov frontend
  package.json
  src/assets/sass/patterns/_pba.scss
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-478

#532 EXUI_AO_4.0.25_Release
  Jenkinsfile_CNP
  package.json
  src/app/app.constants.ts
  src/app/app.module.ts
  src/assets/sass/patterns/_pba.scss
  src/caseworker-ref-data/caseworker-ref-data.module.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/org-manager.module.ts
  src/shared/shared.module.ts
  test/e2e/config/fullfunctional.conf.js
  test/e2e/features/app/deleteActiveOrganisation.feature
  test/e2e/features/pageObjects/approveOrganisationObjects.js
  test/e2e/features/pageObjects/organisationListPage.js
  test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
  test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
  test/ngIntegration/util/browserUtil.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-532

#540 fix template link
  src/caseworker-ref-data/components/caseworker-details/caseworker-details.component.html
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-540

#542 Update known issue list for CVEs
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-542

#543 Update known issue list for CVEs
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-543

#544 Staff_Data_Upload_Template.xlsx new version
  staff/Staff_Data_Upload_Template.xlsx
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-544
