Repository hmcts/rpx-xui-approve-org, pull requests merged in 2022-07, with the labels that each got.

#644 EUI-5865: Reject a newly registered organisation.
  test/e2e/features_ver2.0/app/approveOrganisation.feature
  test/e2e/features_ver2.0/app/organisationUnderReview.feature
  test/e2e/features_ver2.0/app/rejectOrganisation.feature
  test/e2e/features_ver2.0/pageObjects/organisationDetailsPage.js
  test/e2e/features_ver2.0/step_definitions/steps/confirmDecision.steps.js
  test/e2e/features_ver2.0/step_definitions/steps/organisationDetails.steps.js
  test/e2e/features_ver2.0/step_definitions/steps/organisationList.steps.js
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-644

#657 feature/template-V1.14
  charts/xui-ao-webapp/Chart.yaml
  staff/Staff_Data_Upload_Template.xlsx
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-657

#661 EUI-5986-approve org user list pagination
  api/allUserListWithoutRoles/index.ts
  api/organisation/index.ts
  api/routes.ts
  package.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/org-manager/containers/organisation-details/organisation-details.component.html
  src/org-manager/containers/organisation-details/organisation-details.component.spec.ts
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/services/organisation.service.spec.ts
  src/org-manager/services/organisation.service.ts
  src/org-manager/services/users.service.ts
  src/org-manager/store/actions/organisations.actions.spec.ts
  src/org-manager/store/actions/organisations.actions.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/org-manager/store/reducers/organisation.reducer.spec.ts
  test/integration/tests/get_Organisation_User_Details.ts
  test/nodeMock/mockdata/usersList.js
  test/nodeMock/reqResMapping.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-661

#668 Upgrade node basechart
  charts/xui-ao-webapp/Chart.yaml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-668

#669 remove telemetry api call for requests
  api/application.ts
  api/configuration/index.ts
  api/lib/appInsights.ts
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-669
