Repository hmcts/rpx-xui-approve-org, pull requests merged in 2022-03, with the labels that each got.

#593 Quick link functionality
  src/org-manager/components/index.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/components/organisation-details-info/organisation-details-info.component.spec.ts
  src/org-manager/components/quick-links/quick-links.component.html
  src/org-manager/components/quick-links/quick-links.component.spec.ts
  src/org-manager/components/quick-links/quick-links.component.ts
  src/org-manager/components/quick-links/quick-links.scss
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-593

#597 cve supression
  README.md
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-597

#595 Search across tabs functionality
  src/org-manager/containers/active-organisations/active-organisations.component.ts
  src/org-manager/containers/home/home.component.spec.ts
  src/org-manager/containers/organisation-list/organisation-list.component.ts
  src/org-manager/containers/pending-organisations/pending-organisations.component.ts
  src/org-manager/containers/pending-pbas/pending-pbas.component.ts
  src/org-manager/containers/search-organisations-form/search-organisations-form.component.html
  src/org-manager/containers/search-organisations-form/search-organisations-form.component.spec.ts
  src/org-manager/containers/search-organisations-form/search-organisations-form.component.ts
  src/org-manager/services/organisation.service.ts
  src/shared/services/session-storage.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-595

#598 Upgrade node base chart
  Dockerfile
  charts/xui-ao-webapp/Chart.yaml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-598

#604 cve supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-604

#607 CVE Supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-607

#608 CVEs tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-608

#609 CVE Suppression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-609

#611 cve temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-611

#606 E UI 4339 intergrate with pba add remove
  package.json
  src/org-manager/components/index.ts
  src/org-manager/containers/edit-details/edit-details.component.html
  src/org-manager/containers/edit-details/edit-details.component.spec.ts
  src/org-manager/containers/edit-details/edit-details.component.ts
  src/org-manager/containers/organisation-details/organisation-details.component.spec.ts
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/models/errorHeader.model.ts
  src/org-manager/models/organisation.ts
  src/org-manager/models/pbaValidation.model.ts
  src/org-manager/models/pendingPaymentAccount.model.ts
  src/org-manager/org-manager.constants.ts
  src/org-manager/services/organisation.service.ts
  test/accessibility/helpers/pa11yUtil.js
  test/accessibility/tests/activeOrgUsersTab.js
  test/accessibility/tests/orgUpdateApprove.js
  test/nodeMock/reqResMapping.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-606
