Repository hmcts/rpx-xui-approve-org, pull requests merged in 2022-08, with the labels that each got.

#670 CVE fixes
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-670

#671 cve fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-671

#674 CVE/16 08 2022
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-674

#676 cve
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-676

#677 Add backstage configuration file
  catalog-info.yaml
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-677
