Repository hmcts/rpx-xui-approve-org, pull requests merged in 2022-04, with the labels that each got.

#612 E UI 4339 intergrate with pba add remove
  src/app/containers/app/app.component.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/containers/approve-organisation/approve-organisation.component.ts
  src/org-manager/containers/delete-organisation/delete-organisation.component.spec.ts
  src/org-manager/containers/delete-organisation/delete-organisation.component.ts
  src/org-manager/containers/edit-details/edit-details.component.html
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/containers/pending-pbas/pending-pbas.component.html
  src/org-manager/containers/review-organisation/review-organisation.component.spec.ts
  src/org-manager/containers/review-organisation/review-organisation.component.ts
  src/org-manager/services/organisation.service.ts
  src/services/auth/auth.guard.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-612

#614 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-614

#623 CVEs temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-623

#622 E UI 5576 user tab gone
  .vscode/launch.json
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/org-manager/components/new-pbas-confirm/new-pbas-confirm.component.spec.ts
  src/org-manager/components/new-pbas-info/new-pbas-info.component.html
  src/org-manager/components/new-pbas-info/new-pbas-info.component.spec.ts
  src/org-manager/components/new-pbas-info/new-pbas-info.component.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/components/organisation-details-info/organisation-details-info.component.ts
  src/org-manager/components/pba-account-approval/pba-account-approval.component.ts
  src/org-manager/containers/edit-details/edit-details.component.ts
  src/org-manager/containers/new-pbas/new-pbas.component.spec.ts
  src/org-manager/containers/new-pbas/new-pbas.component.ts
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/mock/pending-organisation.mock.ts
  src/org-manager/models/organisation.ts
  src/org-manager/services/organisation.service.spec.ts
  src/org-manager/services/pending-organisation.service.spec.ts
  src/org-manager/store/reducers/organisation.reducer.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-622

#621 eui-5275 implentation
  .vscode/launch.json
  api/organisation/index.ts
  src/org-manager/components/new-pbas-info/new-pbas-info.component.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.ts
  src/org-manager/containers/edit-details/edit-details.component.ts
  src/org-manager/containers/new-pbas/new-pbas.component.spec.ts
  src/org-manager/containers/new-pbas/new-pbas.component.ts
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/store/reducers/organisation.reducer.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-621

#625 CVEs temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-625

#626 yarn and imp
  src/org-manager/containers/pending-pbas/pending-pbas.component.html
  src/org-manager/containers/pending-pbas/pending-pbas.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-626

#624 yarn audit implementation
  api/updatePba/index.ts
  src/org-manager/containers/pending-pbas/pending-pbas.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-624

#629 CVEs temp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-629

#633 yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-633

#634 impl
  api/updatePba/index.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-634
