Repository hmcts/rpx-xui-approve-org, pull requests merged in 2022-05, with the labels that each got.

#637 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-637

#638 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-638

#641 Login Logout changes for new approve org. webapp.
  test/e2e/features/pageObjects/loginLogoutObjects.js
  test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
  test/e2e/features/step_definitions/steps/loginLogout.steps.js
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-641

#643 CVEs tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-643

#646 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-646
