Repository hmcts/rpx-xui-approve-org, pull requests merged in 2022-09, with the labels that each got.

#679 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-679

#680 AO port conflict issue fix.
  angular.json
  package.json
  proxyTest.config.json
  test/nodeMock/app.js
  test/nodeMock/availablePortFinder.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-680

#681 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-681

#682 v15
  Staff_Data_Upload_Template.xlsx
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-682

#684 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-684
