Repository hmcts/rpx-xui-approve-org, pull requests merged in 2022-10, with the labels that each got.

#685 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-685

#686 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-686

#687 Mutation Config File template modification after upgrade to Angular 11.
  stryker.node.conf.js
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-687
