Repository hmcts/rpx-xui-approve-org, pull requests merged in 2022-02, with the labels that each got.

#565 View new PBA's (Display Stories)
  src/org-manager/components/index.ts
  src/org-manager/components/new-pbas-info/new-pbas-info.component.html
  src/org-manager/components/new-pbas-info/new-pbas-info.component.spec.ts
  src/org-manager/components/new-pbas-info/new-pbas-info.component.ts
  src/org-manager/components/pba-account-approval/pba-account-approval.component.html
  src/org-manager/components/pba-account-approval/pba-account-approval.component.spec.ts
  src/org-manager/components/pba-account-approval/pba-account-approval.component.ts
  src/org-manager/containers/index.ts
  src/org-manager/containers/new-pbas/index.ts
  src/org-manager/containers/new-pbas/new-pbas.component.html
  src/org-manager/containers/new-pbas/new-pbas.component.spec.ts
  src/org-manager/containers/new-pbas/new-pbas.component.ts
  src/org-manager/containers/pending-pbas/pending-pbas.component.html
  src/org-manager/org-manager.routing.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-565

#569 cve supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-569

#570 cve supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-570

#574 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-574

#566 EUI-4252 pending and under review implementation
  package.json
  src/assets/sass/application.scss
  src/assets/sass/patterns/_check-your-answers.scss
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/components/organisation-details-info/organisation-details-info.component.spec.ts
  src/org-manager/containers/organisation-details/organisation-details.component.html
  src/org-manager/containers/pending-organisations/pending-organisations.component.html
  test/accessibility/helpers/pa11yUtil.js
  test/accessibility/reporter/customReporter.js
  test/accessibility/tests/deleteOrg.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-566

#577 cve suppresion
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-577

#568 Approve PBA submit functionality
  src/org-manager/components/index.ts
  src/org-manager/components/new-pbas-confirm/new-pbas-confirm.component.html
  src/org-manager/components/new-pbas-confirm/new-pbas-confirm.component.spec.ts
  src/org-manager/components/new-pbas-confirm/new-pbas-confirm.component.ts
  src/org-manager/components/new-pbas-info/new-pbas-info.component.html
  src/org-manager/components/new-pbas-info/new-pbas-info.component.spec.ts
  src/org-manager/components/new-pbas-info/new-pbas-info.component.ts
  src/org-manager/components/pba-account-approval/pba-account-approval.component.html
  src/org-manager/components/pba-account-approval/pba-account-approval.component.spec.ts
  src/org-manager/components/pba-account-approval/pba-account-approval.component.ts
  src/org-manager/components/pba-account-decision/pba-account-decision.component.html
  src/org-manager/components/pba-account-decision/pba-account-decision.component.spec.ts
  src/org-manager/components/pba-account-decision/pba-account-decision.component.ts
  src/org-manager/containers/new-pbas/new-pbas.component.html
  src/org-manager/containers/new-pbas/new-pbas.component.spec.ts
  src/org-manager/containers/new-pbas/new-pbas.component.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-568

#563 EUI-3736 no data implimented
  src/org-manager/containers/organisation-list/organisation-list.component.ts
  src/org-manager/containers/pending-organisations/pending-organisations.component.html
  src/org-manager/containers/pending-pbas/pending-pbas.component.html
  src/org-manager/containers/pending-pbas/pending-pbas.component.spec.ts
  src/org-manager/containers/pending-pbas/pending-pbas.component.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-563

#579 Multiple PBA's - Confirm decision happy
  api/updatePba/index.ts
  src/models/confirm-new-pba.model.ts
  src/models/notification-banner-type.enum.ts
  src/org-manager/components/new-pbas-confirm/new-pbas-confirm.component.html
  src/org-manager/components/new-pbas-confirm/new-pbas-confirm.component.spec.ts
  src/org-manager/components/new-pbas-confirm/new-pbas-confirm.component.ts
  src/org-manager/components/notification-banner/notification-banner.component.html
  src/org-manager/components/notification-banner/notification-banner.component.ts
  src/org-manager/components/pba-account-approval/pba-account-approval.component.html
  src/org-manager/containers/home/home.component.html
  src/org-manager/containers/home/home.component.spec.ts
  src/org-manager/containers/home/home.component.ts
  src/org-manager/containers/new-pbas/new-pbas.component.spec.ts
  src/org-manager/containers/new-pbas/new-pbas.component.ts
  src/org-manager/services/pba.service.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-579

#580 Upgrade node base chart to 2.4.0
  charts/xui-ao-webapp/Chart.yaml
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-580

#583 Feature/e UI 3737 new pba unhappy path
  src/org-manager/components/new-pbas-confirm/new-pbas-confirm.component.spec.ts
  src/org-manager/components/new-pbas-info/new-pbas-info.component.html
  src/org-manager/components/new-pbas-info/new-pbas-info.component.spec.ts
  src/org-manager/components/new-pbas-info/new-pbas-info.component.ts
  src/org-manager/components/pba-account-approval/pba-account-approval.component.html
  src/org-manager/components/pba-account-approval/pba-account-approval.component.spec.ts
  src/org-manager/components/pba-account-approval/pba-account-approval.component.ts
  test/accessibility/tests/activeOrgUsersTab.js
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-583

#589 Feature/e UI 3726 new registrations happy path
  src/org-manager/containers/home/home.component.html
  src/org-manager/containers/home/home.component.ts
  src/org-manager/containers/review-organisation/review-organisation.component.html
  src/org-manager/containers/review-organisation/review-organisation.component.ts
  src/org-manager/services/pending-organisation.service.spec.ts
  src/org-manager/services/pending-organisation.service.ts
  src/org-manager/store/actions/organisations.actions.spec.ts
  src/org-manager/store/actions/organisations.actions.ts
  src/org-manager/store/effects/organisation.effects.spec.ts
  src/org-manager/store/effects/organisation.effects.ts
  src/org-manager/store/reducers/organisation.reducer.spec.ts
  src/org-manager/store/reducers/organisation.reducer.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-589
