Repository hmcts/rpx-xui-approve-org, pull requests merged in 2022-01, with the labels that each got.

#549 node base chart upgrade
  Jenkinsfile_nightly
  charts/xui-ao-webapp/Chart.yaml
  package.json
  projects/gov-ui/src/lib/components/gov-uk-main-wrapper/gov-uk-main-wrapper.component.ts
  sonar-project.properties
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/accessibility/accessibility.component.html
  src/app/components/cookie-policy/cookie-policy.component.html
  src/app/components/not-authorised/not-authorised.component.html
  src/app/components/privacy-policy/privacy-policy.component.html
  src/app/components/service-down/service-down.component.html
  src/app/components/signed-out/signed-out.component.html
  src/app/components/terms-and-conditions/terms-and-conditions.component.html
  src/app/containers/app/app.component.html
  src/app/containers/app/app.component.spec.ts
  src/app/containers/app/app.component.ts
  src/app/store/actions/app.actions.spec.ts
  src/app/store/actions/app.actions.ts
  src/app/store/reducers/app.reducer.spec.ts
  src/app/store/reducers/app.reducer.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/assets/sass/application.scss
  src/caseworker-ref-data/components/caseworker-details/caseworker-details.component.html
  src/caseworker-ref-data/components/upload-info-details/upload-info-details.component.html
  src/caseworker-ref-data/components/upload-info-partial-success/upload-info-partial-success.html
  src/org-manager/components/notification-banner/notification-banner.component.html
  src/org-manager/containers/active-organisations/active-organisations.component.html
  src/org-manager/containers/active-organisations/active-organisations.component.spec.ts
  src/org-manager/containers/active-organisations/active-organisations.component.ts
  src/org-manager/containers/approve-organisation-success/approve-organisation-success.component.html
  src/org-manager/containers/approve-organisation/approve-organisation.component.html
  src/org-manager/containers/delete-organisation-success/delete-organisation-success.component.html
  src/org-manager/containers/delete-organisation/delete-organisation.component.html
  src/org-manager/containers/pending-organisations/pending-organisations.component.html
  src/org-manager/containers/pending-organisations/pending-organisations.component.spec.ts
  src/org-manager/containers/pending-organisations/pending-organisations.component.ts
  src/org-manager/containers/reinvite-user-success/reinvite-user-success.component.html
  src/org-manager/org-manager.routing.ts
  test/accessibility/reporter/customReporter.js
  test/e2e/features/pageObjects/approveOrganisationObjects.js
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-549

#553 cve supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-553

#554 cve-supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-554

#556 CVE Supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-556

#557 cve supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-557

#560 cve supression
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-560

#562 Add CVEs to known list
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-562

#561 Enable Fortify on nightly
  Jenkinsfile_nightly
  package.json
  test/java/.gitignore
  test/java/build.gradle
  test/java/config/fortify-client.properties
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
  test/java/settings.gradle
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-561
