Repository hmcts/rpx-xui-approve-org, pull requests merged in 2023-06, with the labels that each got.

#742 Suppress CVEs
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-742

#744 EXUI-268 Step 1: Add Redis V6 Instance
  infrastructure/main.tf
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, add-or-update, rel:xui-ao-webapp-pr-744

#745 EXUI-268 Step 2: Point to Redis V6 instance
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/values.yaml
Labels: ns:xui, prd:xui, add-or-update, rel:xui-ao-webapp-pr-745
