Repository hmcts/rpx-xui-approve-org, pull requests merged in 2023-09, with the labels that each got.

#767 EXUI-705: Automated Suppression Updates
  .github/workflows/dependency-check.yml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-767

#770 Bug/ex UI 856 ao pipeline failure fix
  Jenkinsfile_nightly
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-770

#773 added renovate json file
  .github/renovate.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-773

#779 EXUI-852: NullInjectorError: R3InjectorError(ut)[i -> i -> i]:
  src/app/app.module.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-779
