Repository hmcts/rpx-xui-approve-org, pull requests merged in 2023-07, with the labels that each got.

#741 EUI-8429: Fix pact publish issue
  api/test/pact/publish/publish.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-741

#747 Disable PACT test until aligned
  api/test/pact/pact-tests/feePay/getAccountById.spec.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-747

#748 EXUI-435 - response code for api call changed from 201 to 200.
  README.md
  api/test/pact/pact-tests/rdProfessional/updatePbaAccounts.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-748

#763 update suppressions
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-763

#761 Temp disable flaky test scenarios and assertions
  test/e2e/config/crossbrowser.conf.js
  test/e2e/config/fullfunctional.conf.js
  test/e2e/config/functional.conf.js
  test/e2e/config/smoke.conf.js
  test/e2e/features/app/search.feature
  test/integration/tests/get_PBA_Account_names.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-761
