Repository hmcts/rpx-xui-approve-org, pull requests merged in 2023-10, with the labels that each got.

#790 Audit fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-790

#799 Update Chart.yaml
  charts/xui-ao-webapp/Chart.yaml
  charts/xui-ao-webapp/values.yaml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-799

#804 yarn audit command for pipeline fixes
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-804
