Repository hmcts/rpx-xui-approve-org, pull requests merged in 2023-01, with the labels that each got.

#710 Update AO redis chart and CVE
  charts/xui-ao-webapp/Chart.yaml
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-710

#712 cve tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-712

#714 cve tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-714

#705 Bug/e UI 7301 under review orgs rejection
  package.json
  src/environments/environment.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/components/organisation-details-info/organisation-details-info.component.spec.ts
  src/org-manager/containers/delete-organisation/delete-organisation.component.spec.ts
  src/org-manager/containers/delete-organisation/delete-organisation.component.ts
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/mock/pending-organisation.mock.ts
  src/org-manager/services/pending-organisation.service.spec.ts
  src/org-manager/services/pending-organisation.service.ts
  src/org-manager/store/actions/organisations.actions.spec.ts
  src/org-manager/store/actions/organisations.actions.ts
  src/org-manager/store/effects/organisation.effects.spec.ts
  src/org-manager/store/effects/organisation.effects.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-705

#715 disable pa11y tests.
  package.json
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-715

#716 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-716

#718 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-718

#720 CVE tmp fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-720
