Repository hmcts/rpx-xui-approve-org, pull requests merged in 2023-11, with the labels that each got.

#807 dependency yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-807

#808 yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-808

#809 yarn audit fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-809

#758 Bug/e UI 8521
  api/test/pact/pact-tests/feePay/getAccountById.spec.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-758

#753 PACT tests for the POST organisations
  api/test/pact/pact-tests/rdProfessional/postOrganisation.spec.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-753

#751 Fix pact test
  api/test/pact/pact-tests/s2s/postToS2S.spec.ts
  api/test/pactFixtures.ts
  api/test/pactUtil.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-751

#811 yarn audit
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-811

#812 fix services
  src/app/utils/app-utils.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/components/organisation-details-info/organisation-details-info.component.ts
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/models/organisation.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-812

#814 yarn audit pipeline fix
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-814

#813 Bug/e UI 8965 display correction
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/components/organisation-details-info/organisation-details-info.component.ts
  src/org-manager/models/organisation.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-813

#810 EUI-8986 Consolidate approve organisation pact tests
  api/test/pact/pact-tests/feePay/getAccountById.spec.ts
  api/test/pact/pact-tests/rdProfessional/postOrganisation.spec.ts
  api/test/pact/pact-tests/s2s/postToS2S.spec.ts
  api/test/pactFixtures.ts
  api/test/pactUtil.ts
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-810

#815 yarn audit file change
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-815

#798 Consume services to access from org API
  api/test/pact/pact-tests/feePay/getAccountById.spec.ts
  api/test/pact/pact-tests/rdProfessional/postOrganisation.spec.ts
  api/test/pact/pact-tests/s2s/postToS2S.spec.ts
  api/test/pactFixtures.ts
  api/test/pactUtil.ts
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/org-manager/components/new-pbas-confirm/new-pbas-confirm.component.spec.ts
  src/org-manager/components/organisation-details-info/organisation-details-info.component.html
  src/org-manager/components/organisation-details-info/organisation-details-info.component.ts
  src/org-manager/containers/organisation-details/organisation-details.component.ts
  src/org-manager/models/organisation.ts
  src/org-manager/services/organisation.service.spec.ts
  src/org-manager/services/pending-organisation.service.spec.ts
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-798
