Repository hmcts/rpx-xui-approve-org, pull requests merged in 2024-06, with the labels that each got.

#846 Remove username from Redis connection string
  infrastructure/main.tf
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, aat/add-or-update, prod/add-or-update, rel:xui-ao-webapp-pr-846

#843 exui-1977-added addressLine3
  src/app/utils/app-utils.spec.ts
  src/app/utils/app-utils.ts
  src/org-manager/components/organisation-address/organisation-address.component.html
  src/org-manager/models/organisation.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-843

#844 EXUI-2013: Resolve crypto-js CVE
  package.json
  src/app/services/cryptoWrapper.ts
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-844
