Repository hmcts/rpx-xui-approve-org, pull requests merged in 2024-01, with the labels that each got.

#824 Updated terraform version
  infrastructure/.terraform-version
  infrastructure/provider.tf
Labels: ns:xui, prd:xui, no-changes, rel:xui-ao-webapp-pr-824

#821 Remove temporary Excel files
  test/data/~$Staff Data Upload Template V1.14.xlsx
  test/data/~$Staff Data Upload Template V2.0.1.xlsx
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-821

#827 cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-827
