Repository hmcts/rpx-xui-approve-org, pull requests merged in 2025-09, with the labels that each got.

#926 exui 584 tough cookie
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-926

#931 cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-931

#932 exui-3500-cve
  yarn-audit-known-issues
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-932
