Repository hmcts/rpx-xui-approve-org, pull requests merged in 2025-04, with the labels that each got.

#870 CME-385: OCI Images
  charts/xui-ao-webapp/Chart.yaml
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-870

#873 EXUI-2974 - update fortify version
  api/server.ts
  charts/xui-ao-webapp/Chart.yaml
  package.json
  playwright_tests/helpers/login.ts
  playwright_tests/org-workflows.test.ts
  test/java/build.gradle
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-873

#871 CME-378-node 20
  .github/workflows/dependency-check.yml
  .nvmrc
  .yarn/install-state.gz
  Dockerfile
  api/test/pact/pact-tests/idam/oidc.spec.ts
  package-lock.json
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-871

#875 exui-2984 - Add status column to Active Organisations tab
  playwright_tests/active-org.test.ts
  src/org-manager/containers/active-organisations/active-organisations.component.html
  src/org-manager/containers/pending-organisations/pending-organisations.component.html
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-875

#872 exui-2909 - add new govuk coat of arms to global footer
  src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
  src/assets/images/govuk-crest.svg
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-872

#879 Added new Civil role WLU Administrator
  staff/Staff_Data_Upload_Template.xlsx
Labels: ns:xui, prd:xui, rel:xui-ao-webapp-pr-879
