Repository hmcts/rpx-xui-approve-org, pull requests merged in 2025-07, with the labels that each got.

#899 CME-495 update terraform to create app insights connection string
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:xui, prd:xui, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:xui-ao-webapp-pr-899

#900 bump yarn to v4
  .yarn/install-state.gz
  .yarn/releases/yarn-3.6.3.cjs
  .yarn/releases/yarn-4.9.2.cjs
  .yarnrc.yml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-900

#902 Update org-workflows.test.ts
  playwright_tests/org-workflows.test.ts
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-902

#908 EXUI-3339 - Fix CVE vulnerability in AO - form-data
  package.json
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-908
