Repository hmcts/rpx-xui-approve-org, pull requests merged in 2025-01, with the labels that each got.

#856 Add content security from node-lib
  api/.yarn/install-state.gz
  api/application.ts
  charts/xui-ao-webapp/values.preview.template.yaml
  config/default.json
  package-lock.json
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm, rel:xui-ao-webapp-pr-856

#859 CME-321: Upgrade azurerm
  infrastructure/main.tf
  infrastructure/provider.tf
Labels: ns:xui, prd:xui, aat/add-or-update, prod/no-changes, rel:xui-ao-webapp-pr-859

#863 EXUI-2707 - Add suite of playwright tests to use in crossbrowser
  .gitignore
  package.json
  playwright.config.ts
  playwright_tests/active-org.test.ts
  playwright_tests/config/config.ts
  playwright_tests/helpers/login.ts
  playwright_tests/helpers/navigate.ts
  playwright_tests/helpers/register-org.ts
  playwright_tests/helpers/string.ts
  playwright_tests/helpers/tables.ts
  playwright_tests/login.test.ts
  playwright_tests/org-workflows.test.ts
  playwright_tests/tabs-load.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:xui, prd:xui, enable_keep_helm
